"""
SSI Pipeline — Austria v4.3 ingestion, shared base layer.

Country-parallel of Mexico + Norway _base.py.  Reuses the country-agnostic
dataclasses via re-export from Canada _base, and overlays Austria-specific
paths + tolerance config + audit sidecar filename convention.
"""

from __future__ import annotations

import hashlib
import json
import logging
from pathlib import Path

# Re-export the country-agnostic dataclasses from Canada _base
from ..canada._base import (
    SubstationRecord,
    TransmissionLineRecord,
    IngestionResult,
    apply_bounds_filter as _apply_bounds_generic,
    assert_line_parity,
    now_utc_iso,
)

logger = logging.getLogger(__name__)

# ── Paths ────────────────────────────────────────────────────────────────
PIPELINE_DIR = Path(__file__).resolve().parent.parent.parent
REPO_ROOT = PIPELINE_DIR.parent.parent
AUSTRIA_BOUNDS_JSON = REPO_ROOT / "austria" / "bounds.json"
AUSTRIA_TOLERANCE_JSON = REPO_ROOT / "cross_border_tolerances.json"
AUSTRIA_DATA_DIR = PIPELINE_DIR / "data" / "austria"
AUSTRIA_CACHE_DIR = AUSTRIA_DATA_DIR / "_osm_cache"


# ── Discipline #36 with Austria 100m default tolerance ───────────────────
def apply_bounds_filter(records, *, tolerance_km: float | None = None):
    """Austria bounds filter with 100m default tolerance.

    Austria bounds already remediated per task #56 (2026-06-24 commit 86d7c9df).
    No fjord/coastline complexity — 100m tolerance adequate.
    """
    if tolerance_km is None:
        try:
            tol_cfg = json.loads(AUSTRIA_TOLERANCE_JSON.read_text(encoding="utf-8"))
            tolerance_km = float(
                tol_cfg.get("per_country", {}).get("austria", {}).get("tolerance_km", 0.1)
            )
        except (FileNotFoundError, json.JSONDecodeError, KeyError, TypeError):
            tolerance_km = 0.1
    return _apply_bounds_generic(
        records, country_slug="austria", tolerance_km=tolerance_km
    )


# ── Audit sidecar (§5ter contract) ───────────────────────────────────────
def emit_audit_sidecar(
    result: IngestionResult,
    *,
    output_dir: Path | None = None,
    parity_findings: list[str] | None = None,
    parent_preflight_yaml: str = "austria/v4_3-ingestion-audit-austria-preflight.yaml",
) -> Path:
    """Emit Austria audit sidecar mirroring Canada + Norway + Mexico convention."""
    if output_dir is None:
        output_dir = AUSTRIA_DATA_DIR
    output_dir.mkdir(parents=True, exist_ok=True)
    slug = result.source_id.lower().replace("_", "-")
    if slug.startswith("at-"):
        slug = slug[len("at-c") + 1 :]
    out_path = output_dir / f"v4_3-ingestion-audit-austria-{slug}.yaml"

    lines = [
        "# SSI Index v4.3 workstream — Austria ingestion fetch audit",
        "# Auto-generated by scripts/pipeline/ingestion/austria/_base.py::emit_audit_sidecar",
        f"# Parent pre-flight: {parent_preflight_yaml}",
        "",
        "schema_version: v4_3-ingestion-audit-fetch-1",
        "country_slug: austria",
        f"source_id: {result.source_id}",
        f'fetched_at_utc: "{result.fetched_at_utc}"',
        f"source_url: {result.source_url or 'null'}",
        f"raw_bytes_fetched: {result.raw_bytes_fetched}",
        f"raw_sha256: {result.raw_sha256 or 'null'}",
        f"provincial_scope: {result.provincial_scope or 'null'}",
        "",
        "empirical_counts:",
        f"  substations: {len(result.substations)}",
        f"  transmission_lines: {len(result.transmission_lines)}",
        "",
        "discipline_41_line_parity:",
    ]
    for f in parity_findings or []:
        lines.append(f"  - {json.dumps(f)}")
    lines += ["", "warnings:"]
    for w in result.warnings:
        lines.append(f"  - {json.dumps(w)}")
    lines += [
        "",
        "auditability_chain:",
        f"  parent_preflight: {parent_preflight_yaml}",
        "  step_2_fetch: austria/v4_3-ingestion-audit-austria-fetch.yaml",
        "  commit_hash_placeholder: TBD_at_L1_connector_merge",
        "  ci_job_url_placeholder: TBD_at_L1_connector_merge",
        "  downstream_deliverable: austria/ssi-data.json (via federation layer)",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote audit sidecar %s (%d bytes)", out_path, out_path.stat().st_size)
    return out_path


# ── Cache helpers ────────────────────────────────────────────────────────
def cache_path_for(url: str, *, ext: str = ".json") -> Path:
    AUSTRIA_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    key = hashlib.sha256(url.encode("utf-8")).hexdigest()[:16]
    return AUSTRIA_CACHE_DIR / f"{key}{ext}"


__all__ = [
    "SubstationRecord",
    "TransmissionLineRecord",
    "IngestionResult",
    "apply_bounds_filter",
    "assert_line_parity",
    "emit_audit_sidecar",
    "cache_path_for",
    "now_utc_iso",
    "AUSTRIA_BOUNDS_JSON",
    "AUSTRIA_TOLERANCE_JSON",
    "AUSTRIA_DATA_DIR",
    "AUSTRIA_CACHE_DIR",
]
