"""
SSI Pipeline — Mexico v4.23 ingestion, shared base layer.

Country-parallel of Norway _base.py.  Reuses the country-agnostic dataclasses
(SubstationRecord + TransmissionLineRecord + IngestionResult) via re-export
from Canada _base, and overlays Mexico-specific paths + tolerance config +
audit sidecar filename convention.
"""

from __future__ import annotations

import hashlib
import json
import logging
from pathlib import Path

from ...utils.tolerance import resolve_boundary_tolerance_km

# Re-export the country-agnostic dataclasses from Canada _base (single canonical
# schema across all v4.23 workstreams so federation can operate uniformly)
from ..canada._base import (
    SubstationRecord,
    TransmissionLineRecord,
    IngestionResult,
    apply_bounds_filter as _apply_bounds_generic,
    assert_line_parity,
    now_utc_iso,
)

logger = logging.getLogger(__name__)

# ── Paths ────────────────────────────────────────────────────────────────
PIPELINE_DIR = Path(__file__).resolve().parent.parent.parent
REPO_ROOT = PIPELINE_DIR.parent.parent
MEXICO_BOUNDS_JSON = REPO_ROOT / "mexico" / "bounds.json"
MEXICO_TOLERANCE_JSON = REPO_ROOT / "cross_border_tolerances.json"
MEXICO_DATA_DIR = PIPELINE_DIR / "data" / "mexico"
MEXICO_CACHE_DIR = MEXICO_DATA_DIR / "_osm_cache"


# ── Discipline #36 with Mexico 100m default tolerance ────────────────────
def apply_bounds_filter(records, *, tolerance_km: float | None = None):
    """Mexico bounds filter with 100m default tolerance.

    Default tolerance = 0.1 km per Mexico cross_border_tolerances.json entry
    (no fjord/coastline complexity that motivated Norway 5km).  US border
    length 3,145 km is longest single-border in v4.23 but 100m is adequate.
    """
    if tolerance_km is None:
        tolerance_km = resolve_boundary_tolerance_km(
            "mexico", module_fallback=0.1
        )
    return _apply_bounds_generic(
        records, country_slug="mexico", tolerance_km=tolerance_km
    )


# ── Audit sidecar (§5ter contract) ───────────────────────────────────────
def emit_audit_sidecar(
    result: IngestionResult,
    *,
    output_dir: Path | None = None,
    parity_findings: list[str] | None = None,
    parent_preflight_yaml: str = "mexico/v4_23-ingestion-audit-mexico-preflight.yaml",
) -> Path:
    """Emit Mexico audit sidecar mirroring Canada + Norway convention."""
    if output_dir is None:
        output_dir = MEXICO_DATA_DIR
    output_dir.mkdir(parents=True, exist_ok=True)
    slug = result.source_id.lower().replace("_", "-")
    if slug.startswith("mx-"):
        slug = slug[len("mx-c") + 1 :]
    out_path = output_dir / f"v4_23-ingestion-audit-mexico-{slug}.yaml"

    lines = [
        "# SSI Index v4.23 workstream — Mexico ingestion fetch audit",
        "# Auto-generated by scripts/pipeline/ingestion/mexico/_base.py::emit_audit_sidecar",
        f"# Parent pre-flight: {parent_preflight_yaml}",
        "",
        "schema_version: v4_23-ingestion-audit-fetch-1",
        "country_slug: mexico",
        f"source_id: {result.source_id}",
        f'fetched_at_utc: "{result.fetched_at_utc}"',
        f"source_url: {result.source_url or 'null'}",
        f"raw_bytes_fetched: {result.raw_bytes_fetched}",
        f"raw_sha256: {result.raw_sha256 or 'null'}",
        f"provincial_scope: {result.provincial_scope or 'null'}",
        "",
        "empirical_counts:",
        f"  substations: {len(result.substations)}",
        f"  transmission_lines: {len(result.transmission_lines)}",
        "",
        "discipline_41_line_parity:",
    ]
    for f in parity_findings or []:
        lines.append(f"  - {json.dumps(f)}")
    lines += ["", "warnings:"]
    for w in result.warnings:
        lines.append(f"  - {json.dumps(w)}")
    lines += [
        "",
        "auditability_chain:",
        f"  parent_preflight: {parent_preflight_yaml}",
        "  step_2_fetch: mexico/v4_23-ingestion-audit-mexico-fetch.yaml",
        "  commit_hash_placeholder: TBD_at_L1_connector_merge",
        "  ci_job_url_placeholder: TBD_at_L1_connector_merge",
        "  downstream_deliverable: mexico/ssi-data.json (via federation layer)",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote audit sidecar %s (%d bytes)", out_path, out_path.stat().st_size)
    return out_path


# ── Cache helpers ────────────────────────────────────────────────────────
def cache_path_for(url: str, *, ext: str = ".json") -> Path:
    MEXICO_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    key = hashlib.sha256(url.encode("utf-8")).hexdigest()[:16]
    return MEXICO_CACHE_DIR / f"{key}{ext}"


__all__ = [
    "SubstationRecord",
    "TransmissionLineRecord",
    "IngestionResult",
    "apply_bounds_filter",
    "assert_line_parity",
    "emit_audit_sidecar",
    "cache_path_for",
    "now_utc_iso",
    "MEXICO_BOUNDS_JSON",
    "MEXICO_TOLERANCE_JSON",
    "MEXICO_DATA_DIR",
    "MEXICO_CACHE_DIR",
]
