"""Sentinel — every country must record which pipeline produced its scores.

WHY THIS TEST EXISTS
────────────────────
Eight countries — france, germany, italy, japan, portugal, spain, sweden, us —
have zero scored substations. They are also, exactly, the eight with
`meta.scoring_pipeline`, `meta.regen_method` and `meta.version` all null. That
is not a coincidence of data state; it is the same fact seen twice.

Between them M-053 retired **471,930** component vectors generated by
`enrich_esg_gaps.py`, and M-054 recovered 56,958 from v4.0.2 backups which are
deliberately held Unclassified pending rescore. Their entire component
population was synthetic, so retiring it emptied them.

WHAT THE INVESTIGATION FOUND (M-066)
────────────────────────────────────
The instinct to "align these eight with the other 31" is the wrong direction,
and this docstring exists so nobody re-derives that the hard way.

There are only two other pipelines in the estate:

  • `digital-twin-<country>` — 26 countries. The metadata itself says
    "(archived)". No code in this repo produces it. The target does not exist.

  • `scripts/score-country.py` — 7 countries. It exists, and it generates
    **every component from MD5 jitter**:

        C = max(0.05, min(0.95, det_var(seed+'C', ref.get('C_base', 0.45), 0.35)))

    Aligning the eight to it would manufacture 471,930 synthetic component
    vectors — precisely what M-052/M-053 retired.

So the eight are not lagging. They are the only part of the cohort that has
been cleaned. The other 31 are scored on components **no pipeline in this repo
can reproduce**; the only component producer that exists is
`ingestion/components.py`, added 20 August 2026, which today covers 2 of 20
metrics. The honest alignment runs the other way.

WHAT THIS PINS
──────────────
1.  No NEW country reaches the unprovenanced state. The ten currently in it are
    frozen in KNOWN_UNPROVENANCED; a country outside that set with a null
    `scoring_pipeline` fails.
2.  The burn-down list cannot go stale. If a listed country gains provenance,
    this test fails and tells you to remove it — so the list shrinks visibly
    instead of quietly outliving the problem.
3.  `scoring_pipeline` values come from a known vocabulary. A new pipeline name
    has to be declared here, which forces the question "what produced this?" to
    be answered before data lands.
4.  Unprovenanced countries do not publish MORE scores than they do today.
    hungary (3,502) and latvia (1,219) publish scores on components whose
    producing pipeline is unrecorded. That is the residual violation; it is
    frozen at its current size so it can only shrink.

Do not xfail this test. If a country legitimately gains a new pipeline, add it
to KNOWN_PIPELINE_PREFIXES in the same commit as the data.

Cross-reference: SSI_DOCUMENT_PRECEDENCE_REGISTER.md §6 · modification-log
M-052 / M-053 / M-066 · SSI_DATA_SOURCE_RECORD.md.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from ._ssi_test_support import load_ssi_data

REPO_ROOT = Path(__file__).resolve().parent.parent

COUNTRIES = sorted(p.parent.name for p in REPO_ROOT.glob("*/ssi-data.json"))

#: Frozen 20 August 2026. This list may SHRINK, never grow.
KNOWN_UNPROVENANCED = frozenset({
    "france", "germany", "hungary", "italy", "japan",
    "latvia", "portugal", "spain", "sweden", "us",
})

#: Every `scoring_pipeline` value must start with one of these.
KNOWN_PIPELINE_PREFIXES = (
    "digital-twin-",              # 26 countries; archived, no producing code
    "scripts/score-country.py",   # 7 countries; det_var component generator
)

#: Scores published by a country whose producing pipeline is unrecorded.
#: Frozen at the current count so the violation can only burn down.
UNPROVENANCED_SCORE_CEILING = {"hungary": 3502, "latvia": 1219}


def _meta(country):
    return json.loads(
        (REPO_ROOT / country / "ssi-data.json").read_text(encoding="utf-8")
    ).get("meta") or {}


@pytest.mark.parametrize("country", COUNTRIES)
def test_no_new_country_lacks_scoring_pipeline(country):
    pipeline = _meta(country).get("scoring_pipeline")
    if country in KNOWN_UNPROVENANCED:
        pytest.skip(
            f"{country} is a known-unprovenanced country, frozen 20 Aug 2026. "
            f"See test_the_burn_down_list_has_not_gone_stale."
        )
    assert pipeline, (
        f"{country} has no `meta.scoring_pipeline`, and is not in the frozen "
        f"burn-down list. A new country has reached the state that left eight "
        f"others with 471,930 synthetic component vectors and no record of what "
        f"produced them. Record the pipeline that generated this data before "
        f"publishing it — and if it is `scripts/score-country.py`, note that "
        f"every component it emits is MD5 jitter (M-066)."
    )


def test_the_burn_down_list_has_not_gone_stale():
    """A listed country that gains provenance must leave the list."""
    graduated = sorted(
        c for c in KNOWN_UNPROVENANCED
        if c in COUNTRIES and _meta(c).get("scoring_pipeline")
    )
    assert not graduated, (
        f"{graduated} now record a `scoring_pipeline` but are still listed in "
        f"KNOWN_UNPROVENANCED. Remove them — the list is a burn-down, and one "
        f"that outlives the problem it describes becomes the stale authority "
        f"this estate keeps paying for."
    )


@pytest.mark.parametrize("country", COUNTRIES)
def test_scoring_pipeline_value_is_from_the_known_vocabulary(country):
    pipeline = _meta(country).get("scoring_pipeline")
    if not pipeline:
        pytest.skip(f"{country} has no scoring_pipeline — covered by the test above")
    assert pipeline.startswith(KNOWN_PIPELINE_PREFIXES), (
        f"{country} declares scoring_pipeline={pipeline!r}, which is not in the "
        f"known vocabulary {KNOWN_PIPELINE_PREFIXES}. If a new pipeline exists, "
        f"add it here in the same commit as the data, and say in the modification "
        f"log what it does with `components` — that question is the whole reason "
        f"this sentinel exists."
    )


@pytest.mark.parametrize("country", sorted(KNOWN_UNPROVENANCED))
def test_unprovenanced_countries_do_not_publish_more_scores(country):
    """The residual violation is frozen at its current size."""
    if country not in COUNTRIES:
        pytest.skip(f"{country} absent from this checkout")
    doc = load_ssi_data(country, REPO_ROOT)
    scored = sum(1 for s in (doc.get("substations") or [])
                 if s.get("R_median") is not None)
    ceiling = UNPROVENANCED_SCORE_CEILING.get(country, 0)
    assert scored <= ceiling, (
        f"{country} publishes {scored:,} scores but its producing pipeline is "
        f"unrecorded (ceiling {ceiling:,}). Either record what produced the "
        f"components these scores rest on, or do not publish them. Scores whose "
        f"inputs cannot be traced to a producer are the M-046 failure with an "
        f"extra step."
    )
