"""
SSI Pipeline — Norway v4.23 ingestion, shared base layer.

Country-parallel of scripts/pipeline/ingestion/canada/_base.py.  Reuses the
country-agnostic dataclasses (SubstationRecord + TransmissionLineRecord +
IngestionResult) via re-export, and overlays Norway-specific paths + tolerance
config + audit sidecar filename convention.
"""

from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from ...utils.tolerance import resolve_boundary_tolerance_km

# Re-export the country-agnostic dataclasses from Canada _base (single canonical
# schema across all v4.23 workstreams so federation can operate uniformly)
from ..canada._base import (
    SubstationRecord,
    TransmissionLineRecord,
    IngestionResult,
    apply_bounds_filter as _apply_bounds_generic,
    assert_line_parity,
    now_utc_iso,
)

logger = logging.getLogger(__name__)

# ── Paths ────────────────────────────────────────────────────────────────
PIPELINE_DIR = Path(__file__).resolve().parent.parent.parent
REPO_ROOT = PIPELINE_DIR.parent.parent
NORWAY_BOUNDS_JSON = REPO_ROOT / "norway" / "bounds.json"
NORWAY_TOLERANCE_JSON = REPO_ROOT / "norway" / "cross_border_tolerances.json"
NORWAY_DATA_DIR = PIPELINE_DIR / "data" / "norway"
NORWAY_CACHE_DIR = NORWAY_DATA_DIR / "_nve_cache"


# ── Discipline #36 with Norway 5-km fjord tolerance ──────────────────────
def apply_bounds_filter(records, *, tolerance_km: float | None = None):
    """Norway bounds filter with fjord-coastline tolerance.

    Default tolerance = 5 km per norway/cross_border_tolerances.json Mode 2
    (fjord + coastline simplification per Discipline #36 second-wave remediation).
    """
    if tolerance_km is None:
        tolerance_km = resolve_boundary_tolerance_km(
            "norway", module_fallback=5.0
        )
    return _apply_bounds_generic(
        records, country_slug="norway", tolerance_km=tolerance_km
    )


# ── Audit sidecar (§5ter contract) ───────────────────────────────────────
def emit_audit_sidecar(
    result: IngestionResult,
    *,
    output_dir: Path | None = None,
    parity_findings: list[str] | None = None,
    parent_preflight_yaml: str = "norway/v4_23-ingestion-audit-norway-preflight.yaml",
) -> Path:
    """Emit Norway audit sidecar mirroring Canada convention."""
    if output_dir is None:
        output_dir = NORWAY_DATA_DIR
    output_dir.mkdir(parents=True, exist_ok=True)
    slug = result.source_id.lower().replace("_", "-")
    if slug.startswith("no-"):
        slug = slug[len("no-c") + 1 :]
    out_path = output_dir / f"v4_23-ingestion-audit-norway-{slug}.yaml"

    lines = [
        "# SSI Index v4.23 workstream — Norway ingestion fetch audit",
        "# Auto-generated by scripts/pipeline/ingestion/norway/_base.py::emit_audit_sidecar",
        f"# Parent pre-flight: {parent_preflight_yaml}",
        "",
        "schema_version: v4_23-ingestion-audit-fetch-1",
        "country_slug: norway",
        f"source_id: {result.source_id}",
        f'fetched_at_utc: "{result.fetched_at_utc}"',
        f"source_url: {result.source_url or 'null'}",
        f"raw_bytes_fetched: {result.raw_bytes_fetched}",
        f"raw_sha256: {result.raw_sha256 or 'null'}",
        f"provincial_scope: {result.provincial_scope or 'null'}",
        "",
        "empirical_counts:",
        f"  substations: {len(result.substations)}",
        f"  transmission_lines: {len(result.transmission_lines)}",
        "",
        "discipline_41_line_parity:",
    ]
    for f in parity_findings or []:
        lines.append(f"  - {json.dumps(f)}")
    lines += ["", "warnings:"]
    for w in result.warnings:
        lines.append(f"  - {json.dumps(w)}")
    lines += [
        "",
        "auditability_chain:",
        f"  parent_preflight: {parent_preflight_yaml}",
        "  step_2_fetch: norway/v4_23-ingestion-audit-norway-fetch.yaml",
        "  step_2b_line_schema: norway/v4_23-ingestion-audit-norway-line-schema.yaml",
        "  commit_hash_placeholder: TBD_at_L1_connector_merge",
        "  ci_job_url_placeholder: TBD_at_L1_connector_merge",
        "  downstream_deliverable: norway/ssi-data.json (via federation layer)",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote audit sidecar %s (%d bytes)", out_path, out_path.stat().st_size)
    return out_path


# ── Cache helpers ────────────────────────────────────────────────────────
def cache_path_for(url: str, *, ext: str = ".xml") -> Path:
    NORWAY_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    key = hashlib.sha256(url.encode("utf-8")).hexdigest()[:16]
    return NORWAY_CACHE_DIR / f"{key}{ext}"


__all__ = [
    "SubstationRecord",
    "TransmissionLineRecord",
    "IngestionResult",
    "apply_bounds_filter",
    "assert_line_parity",
    "emit_audit_sidecar",
    "cache_path_for",
    "now_utc_iso",
    "NORWAY_BOUNDS_JSON",
    "NORWAY_TOLERANCE_JSON",
    "NORWAY_DATA_DIR",
    "NORWAY_CACHE_DIR",
]
